import Head from 'next/head'
import Home from '@component/src/components/Home'

export default function Init({ data }) {
  return (
    <>
      <Head>
        <title>Beer dOt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home products={JSON.parse(data)} />
    </>
  )
}

export async function getServerSideProps() {
  const data = await import('@component/data/products')
  const dataJson = JSON.stringify(data.default)

  return {
    props: {
      data: dataJson,
    },
  }
}
